version: '3.8'
services:
  garderie_educatrice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db_educatrice

  db_educatrice:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: db_educatrice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

  garderie_test:
    image: postgres:13.1
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=garderie_test
    volumes:
      - .dbdatapg:/var/lib/postgresql/data
    ports:
      - 5432:5432
